apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processing-service
  labels:
    app: payment-processing-service
spec:
  replicas: 1
  template:
    metadata:
      name: payment-processing-service
      labels:
        app: payment-processing-service
    spec:
      containers:
        - name: payment-processing-service
          image: ylogosha/payment-processing-service
          ports:
            - containerPort: 3000
      restartPolicy: Always
  selector:
    matchLabels:
      app: payment-processing-service
