apiVersion: v1
kind: Service
metadata:
  name: payment-processing-service
spec:
  selector:
    app: payment-processing-service
  type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http